import ReactMarkdown from 'react-markdown';

interface ReportViewerProps {
    reportText: string;
}

export default function ReportViewer({ reportText }: ReportViewerProps) {
    const handleDownload = () => {
        if (!reportText) return;
        const blob = new Blob([reportText], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Literature_Review_${new Date().toISOString().split('T')[0]}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    if (!reportText) return null;

    return (
        <div className="flex flex-col h-full bg-[#0c0d12]">
            {/* Header */}
            <div className="bg-[#1a1b23] border-b border-white/[0.06] px-6 py-4 flex items-center justify-between z-10 sticky top-0">
                <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center shrink-0">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="text-white">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                    </div>
                    <div>
                        <h2 className="text-white font-semibold flex items-center gap-2">
                            Final Literature Review
                        </h2>
                        <span className="text-xs text-gray-500 font-mono mt-0.5 block">
                            Generated by Gemini 2.5 Pro (1M Context)
                        </span>
                    </div>
                </div>

                <button
                    onClick={handleDownload}
                    className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-sm font-medium text-gray-300 transition-colors cursor-pointer"
                >
                    <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download .md
                </button>
            </div>

            {/* Markdown Body */}
            <div className="flex-1 overflow-y-auto w-full flex justify-center py-10 px-6">
                <article className="prose prose-invert prose-headings:text-gray-100 prose-a:text-blue-400 prose-strong:text-gray-200 w-full max-w-4xl text-gray-300">
                    <ReactMarkdown>
                        {reportText}
                    </ReactMarkdown>
                </article>
            </div>
        </div>
    );
}
